# Generated by Django 4.1.7 on 2023-02-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_college_address_remove_college_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='visibility',
            field=models.CharField(choices=[('1', 'Private'), ('2', 'College'), ('3', 'Public')], default='3', max_length=1),
        ),
    ]
