# Generated by Django 4.1.7 on 2023-02-19 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='visibility',
        ),
        migrations.AddField(
            model_name='note',
            name='department',
            field=models.CharField(choices=[('CE', 'Computer engineering'), ('MH', 'Mechanical engineering'), ('EC', 'Electrical engineering'), ('CH', 'Chemical engineering')], default='CE', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='semester',
            field=models.CharField(choices=[('1', 'semester 1'), ('2', 'semester 2'), ('3', 'semester 3'), ('4', 'semester 4'), ('5', 'semester 5'), ('6', 'semester 6'), ('7', 'semester 7'), ('8', 'semester 8')], default='1', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
