# Generated by Django 4.1.7 on 2023-02-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_userprofile_college_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='description',
        ),
    ]
